export enum ErrorCategory {
  AUTH_ERROR = "AUTH_ERROR",
  QUOTA_ERROR = "QUOTA_ERROR",
  PROVIDER_ERROR = "PROVIDER_ERROR",
  QA_ERROR = "QA_ERROR",
  UPLOAD_ERROR = "UPLOAD_ERROR",
  ASSEMBLY_ERROR = "ASSEMBLY_ERROR",
}
